# Generated by Django 3.1.5 on 2021-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exifview', '0002_auto_20210120_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.ImageField(upload_to='MetaClean/'),
        ),
    ]
