# Generated by Django 3.1.5 on 2021-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exifview', '0003_auto_20210123_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Image_To_Clean',
        ),
    ]
